package com.example.RvOnclick;


import android.Manifest;
import android.arch.persistence.room.Room;
import android.content.Intent;
import android.content.pm.PackageManager;
import android.location.Location;
import android.os.Bundle;
import android.os.Looper;
import android.support.annotation.NonNull;
import android.support.v4.app.ActivityCompat;
import android.support.v4.app.Fragment;
import android.support.v4.content.ContextCompat;
import android.support.v7.widget.DefaultItemAnimator;
import android.support.v7.widget.LinearLayoutManager;
import android.support.v7.widget.RecyclerView;
import android.text.Editable;
import android.text.TextWatcher;
import android.util.Log;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.EditText;
import android.widget.TextView;
import android.widget.Toast;

import com.google.android.gms.location.FusedLocationProviderClient;
import com.google.android.gms.location.LocationCallback;
import com.google.android.gms.location.LocationRequest;
import com.google.android.gms.location.LocationResult;
import com.google.android.gms.location.LocationServices;
import com.google.android.gms.location.LocationSettingsRequest;
import com.google.android.gms.location.SettingsClient;
import com.google.android.gms.tasks.OnFailureListener;
import com.google.android.gms.tasks.OnSuccessListener;

import java.util.ArrayList;
import java.util.List;


/**
 * A simple {@link Fragment} subclass.
 */
public class TabFragment1 extends Fragment implements CustomerAdapter.OnItemClickListener {


    private TextView mTextView;
    EditText etCustomerSearch;
    public static StDatabase stDatabase;
    private FusedLocationProviderClient fusedLocationProviderClient;
    final ApplicationController applicationController = new ApplicationController();
    public RecyclerView recyclerView;
    public CustomerAdapter customerAdapter;
    private String TAG  = "TabFragment1";



    public static List<Customer> customerList, searchableList;


    private CustomerAdapter.OnItemClickListener listener;
    //public CustomerAdapter customerAdapter = new CustomerAdapter(listener,customerList, getActivity());


    public TabFragment1() {
        // Required empty public constructor
    }


    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        // Inflate the layout for this fragment
        View view = inflater.inflate(R.layout.fragment_tab_fragment1, container, false);

        stDatabase = Room.databaseBuilder(getActivity().getApplicationContext(), StDatabase.class, "StDB")
                .allowMainThreadQueries().build();

        customerList = stDatabase.stDao().getEnabledCustomers(false);


        etCustomerSearch = view.findViewById(R.id.et_searchCustomerList);

        recyclerView = (RecyclerView) view.findViewById(R.id.recyclerview);

        recyclerView.setLayoutManager(new LinearLayoutManager(getActivity()));


        customerList = applicationController.sortCustomerList(customerList);


        listener = this;
        customerAdapter = new CustomerAdapter(listener, customerList, getActivity());
        recyclerView.setAdapter(customerAdapter);
        recyclerView.setItemAnimator(new DefaultItemAnimator());

        etCustomerSearch.addTextChangedListener(new TextWatcher() {
            @Override
            public void beforeTextChanged(CharSequence s, int start, int count, int after) {
                //autogenerated - serves no purpose
            }

            @Override
            public void onTextChanged(CharSequence s, int start, int before, int count) {
                //fires up when there's any change in the search text box
                List<Customer> filtered = new ArrayList<>();
                searchableList = stDatabase.stDao().getCustomer();
                for (Customer customer : searchableList) {
                    String searchString;
                    if (customer.getDisplay_name() == null) {
                        searchString = customer.getCustomer_id().toLowerCase();
                    } else {
                        searchString = customer.getCustomer_id().toLowerCase();
                    }
                    String searchedString = etCustomerSearch.getText().toString().toLowerCase();
                    if (searchString.contains(searchedString)) {
                        filtered.add(customer);
                    }
                }
                customerList = applicationController.sortCustomerList(filtered);
                customerAdapter = new CustomerAdapter(listener, customerList, getActivity());
                recyclerView.setAdapter(customerAdapter);
                customerAdapter.notifyDataSetChanged();

            }


            @Override
            public void afterTextChanged(Editable s) {

            }
        });


        return view;
    }



    @Override
    public void onItemClicked(View v, int position) {

        String custCode = customerList.get(position).getCustomer_id();
        //Toast.makeText(getActivity(), custCode, Toast.LENGTH_SHORT).show();
        /*Bundle args = new Bundle();
        args.putString("custCode", custCode);

        DialogFragment_ProductRateInfo df = new DialogFragment_ProductRateInfo();
        df.setArguments(args);
        df.show(getFragmentManager(),"Dialog");*/

        Intent intent = new Intent(getActivity(), CustomerTransactionActivity.class);
        intent.putExtra("custCode", custCode);
        getActivity().startActivity(intent);
    }

    @Override
    public void onResume(){
        etCustomerSearch.selectAll();
        applicationController.showKeyboard(etCustomerSearch,getActivity());
        super.onResume();
    }
}
